### ISSUE TITLE
Script to create the Database itself

### ISSUE THREAD

**Issue by Hamcker** [Behzadkhosravifar/ErrorControlSystem#34]
It's much better to have a little script to create the database itself. I suggest to add this script at the beginning of **Table Creator scripts**, Thus, We'll be able to reduce user need work. By this, the user would only consider the `ServerName`.
Or It's better to choose DB name by default if it's omitted. for example `xxxECS` (which xxx is the application name) is much better than names which developers will choose.

**Comment by Behzadkhosravifar** [comment]
Hi,
This proposal already solved. but the default name of database if it's omitted was good idea.
Thanks for commit, i will try to add that feature as soon.
