### ISSUE TITLE
How to install module on VB.NET project without Startup Module Class

### ISSUE THREAD

**Issue by AFazli** [Behzadkhosravifar/ErrorControlSystem#36]
In VB.NET must be declare a module class for add ErrorControlSystem to project, and now, we need to add it without cleaning.
Please add one example in read me file.

**Comment by Behzadkhosravifar** [comment]
In a VB Project can be declare this model:

In Solution Window:
* My Project
    * Application.myapp
        * Application.Designer.vb

Add startup handler :

```VB
Private Sub Application_Startup(sender as object, e as StartupEventArgs) Handler Me.Startup
   ECS codes...
End Sub
```
