### ISSUE TITLE
Dose Not Found System.Data.SqlServerCe v4.0 assembly at ClickOnce client

### ISSUE THREAD

**Issue by aioubamini** [Behzadkhosravifar/ErrorControlSystem#37]
When i publish the my project that have ErrorControlSystem module, and copied that to clients system then when run it by clicking on __ClickOnce__ published application , throw this exception:
Unable to install or run the application. The application requires that assembly `System.Data.SqlServerCe` be installed in the global assembly cache (GAC) first.

Please contact your system administrator.

**Comment by Behzadkhosravifar** [comment]
Solved by Issue #43
