### ISSUE TITLE
What Prerequisites are need to attach this library?

### ISSUE THREAD

**Issue by Hamcker** [Behzadkhosravifar/ErrorControlSystem#43]
After I published my application, my users notified me about failure of update! because SqlServerCe version 4.0 was need.
So what else libraries like above are need?

**Comment by Behzadkhosravifar** [comment]
Hi,
`SqlServerCe.dll` and `MicrosoftTaskParallelLibrary.dll` are attached to `ErrorControlSystem`.
I try to solve this click once problem now.

**Comment by Behzadkhosravifar** [comment]
In the [new version 4.1.2](https://www.nuget.org/packages/ErrorControlSystem/) , i try to add all dependency assembly to project by nuget package.
Please download new version and try again, if that exceptions again occurred on clickOnce , tell me about.

**Comment by Behzadkhosravifar** [comment]
Any dependency added to ErrorControlSystem without embed resources that added by Nuget package.
