### ISSUE TITLE
A new guard page for the stack cannot be created.

### ISSUE THREAD

**Issue by aioubamini** [Behzadkhosravifar/ErrorControlSystem#53]
After a few seconds of running project the following error occurs my projects:

System Error
---------------------------------------------------------------
A new guard page for the stack cannot be created.
---------------------------------------------------------------
OK

Happy if you help me

**Comment by Behzadkhosravifar** [comment]
This exception occurred only at click-once system! because that is not attach all ECS assembly reference s to client applications like: `SqlCopactEdition x86 and amd64` folders.
